[project]
name = "qownnotes-mobile"
revision = "1.0"

[profiles.development]
ANDROID_DEV_KEYSTORE_PASSWORD = { description = "Android development keystore password" }
ANDROID_DEV_KEY_ALIAS = { description = "Android development key alias" }
ANDROID_DEV_KEY_PASSWORD = { description = "Android development key password" }

[profiles.release]
ANDROID_KEYSTORE_PASSWORD = { description = "Android release keystore password" }
ANDROID_KEY_ALIAS = { description = "Android release key alias" }
ANDROID_KEY_PASSWORD = { description = "Android release key password" }
